### ISSUE TITLE
Proposal for alternative Disclosures data model

### ISSUE THREAD

**Issue by mtaimela** [oauth-wg/oauth-selective-disclosure-jwt#291] opened 2023-06-13 13:22 UTC
https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#section-5.3-2
> The data format for sending the SD-JWT and the Disclosures to the Holder MUST be a series of base64url-encoded values, each separated from the next by a single tilde ('~') character as follows

The tilde is definitely very innovative, but it still introduces interesting mapping challenge. Is there a reason why the Disclosures cannot be signed? If there is no reason to NOT sign the Disclosures, then I do propose an alternative design.

There could be a `Holder Disclosed VC` or so to **aggregate** the `Issuer-Issued Disclosure` AND `SD-JWT`. This will fit into the normal way of treating VCs, stored as is and queried through VP exchange.

Issuer-Issued Disclosures in could be a list.
SD-JWT would be embedded JWT, aka "raw" JWT inside JWT.

JWT in JWT will incur size penalty. If the size of the SD-JWT is an issue, it could be issued in binary presentation. I still would propose to take the size impact.

---
Edit: removed parsing parts as it will just be interesting mapping challenge

**Comment by danielfett** [comment] 2023-06-13 19:08
Hi Matti,

this design was considered and discarded. The problem is that such an approach would mean that both the signed object and the disclosures* are double-base64-encoded, increasing their size considerably. The current approach was chosen because it allows for a relatively compact representation.

*The disclosures need to be protected against modification that would lead to different hash values. For this reason, they are base64 encoded. We did consider a different approach using JSON-in-JSON (see earlier drafts), but that had the potential to introduce subtle problems.

**Comment by Sakurann** [comment] 2023-06-14 05:27
I think https://www.rfc-editor.org/rfc/rfc7797#section-5.2 is pretty clear that 
>    When using the JWS Compact Serialization, unencoded non-detached
   payloads using period ('.') characters would cause parsing errors;
   such payloads MUST NOT be used with the JWS Compact Serialization.

**Comment by mtaimela** [comment] 2023-06-14 05:59
Hi Kristina,

Yes indeed, the unencoded payload, to be part of the "jwt style" serialization, must not have dots in the content.

There is still room to play in the transport channel with "some" encoding OR use the flattened serialisation which doesn't have such limitations, where I think the JSON would be more suitable for the use case.

The outer wrapper could be done "unencoded", and the SD-JWT inside can be JWT. Outer wrapper is always kept by Holder and never given away, so it is just temporary structure allowing signed disclosures and flexible structure.

Any thoughts on this?

**Comment by danielfett** [comment] 2023-06-14 07:28
One design goal was that the default encoding of an SD-JWT (both for issuance and presentation) is URL safe, just like JWTs are URL safe. The JSON serialization does not fulfill this requirement.

**Comment by mtaimela** [comment] 2023-06-14 08:10
Hi Daniel,

Are you referring the SD-JWT as the proof carrier, or the whole specification? The latter imposes issues, but the SD-JWT itself is still JWT, even if the wrapper is Flattened JWS in JSON.

If the target is to issue the SD-JWT and Disclosures inside URL, instead of limiting into payloads, then I fully understand the concatenated string methodology. 

Usually the URL should not contain important information, like email, even as encoded.

**Comment by danielfett** [comment] 2023-06-14 09:15
I'm referring to the issuer-signed part (the JWT) plus the disclosures (we'll clear up terminology soon to call this whole thing "SD-JWT"); both for issuance and presentation.

Actual URLs are only one concern, but, for example, OAuth bearer access tokens are effectively limited to a URL safe character set (plus some, see RFC6750). 

More generally, to enable the use of SD-JWTs in as many use cases as possible that so far used JWTs, we want to be URL safe.

**Comment by alenhorvat** [comment] 2023-06-14 12:49
Hi, all. The topics has been raised before and I agree with Matti's proposal. The current design (for the compact serialised JWS)
- breaks the JWS signature
- introduces an undefined holder binding
- issuer issued claims don't have the possibility to be encrypted

Essentially, the issuer issued disclosures are fully exposed when exchanged via front-channel. Should in those cases encryption be recommended?

Sharing personal information and secrets via URL may result with insecure implementations and practices

**Comment by mtaimela** [comment] 2023-06-14 15:04
Thank you for the support @alenhorvat 

I think it might be helpful to build a very minimal issuance payload, to make it very visible that SD-JWT VC is not touched and it will contain all properties as it currently has.

The proposal here is to get rid of the string concatenation, with a data structure, and to get issuer signature for the Disclosures. Just by modifying this will not affect presentation at all. Of course, currently the presentation side has the string concatenation thingy going on too, so there should to be an alternative model too. These two topics are separate from each other, and the issuance side should be evaluated before the presentation.

The alternatives for presentation side, that would support Disclosures encryption would be: Holder self-issuing a VC before presentation, choosing the disclosures she/he wants to present. This would be carried with-in the VP exchange, next to the SD-JWT.  The self-issued VC should refer to the correct SD-JWT as there might be many. Holder binding would also be covered.

Second alternative approach to disclosing the Disclosures would be just the use of VP itself. There's plenty of room, but there's no way to encrypt these with VCs natural toolings and patterns, so I think the self-issued VC method for presentation should be evaluated.

There definitely are other approaches too.

**Comment by Sakurann** [comment] 2023-06-14 17:50
@alenhorvat 
>breaks the JWS signature

Can you please explain how? Issuers signs over the payload with digests using JWS. and attach disclosures to it.

> introduces an undefined holder binding

The use of Key Binding JWT is optional, but the structure of the Key binding JWT is normatively defined.

> issuer issued disclosures don't have the possibility to be encrypted (or the holder selected disclosures)

Yes, there is. You encrypt the entire string that is comprised of the issuer signed JWT and the Disclosures using JWE.

**Comment by Sakurann** [comment] 2023-06-14 17:54
> Essentially, the issuer issued disclosures are fully exposed when exchanged via front-channel. Should in those cases encryption be recommended?

there is already a section on that https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#name-confidentiality-during-tran

and this is a separate topic than the original question raised. signing over Disclosures will not solve this.

**Comment by Sakurann** [comment] 2023-06-14 17:58
If the attacker can modify the Disclosures, there is a bigger problem going on, and the attack would probably be more effective by inserting an attacker-signed SD-JWT with intercepted valid `nonce` and `aud` values for example. So I still do not see a strong argument to modify the issuance/presentation structure.

**Comment by alenhorvat** [comment] 2023-06-15 04:53
> https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#name-confidentiality-during-tran

Hi, Kristina. I admire all the magnificent work this team is doing.

The current proposal appends information to the JWS. And the appended information can be of two types: issuer issued disclosure, and holder binding. Hence, this document is defining a new signature format for compact serialised JWS. This is also reflected in the newly registered IANA media types specified in the document.

This comment is addressing Compact Serialised JWS

JWS defines media types: JOSE and JOSE+JSON
If my understanding is correct, media types could also be just: JOSE+sd+jwt (and the one with holder binding JWT)
JWS libraries don't recognise the new typ, hence the comment about breaking the JWS implementation.

By inspecting https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf and https://www.rfc-editor.org/rfc/rfc7797, there appeared to be a solution that is compatible with the existing JWS, however, it turns out that one cannot combine two JWS signatures without additional serialisation. Namely, in some cases issuer would like to sign the sd-jwt, but also the issuer issued disclosures to have a proof that it shared everything with the holder.

The only case where we benefit from smaller size is when issuer-issued disclosures are unsigned and when holder selected disclosures are unsigned. Key binding is not securing the payload (it could solve part of the problem)

If holder needs to sign the whole payload (for integrity/nonrepudiation/...), I believe section 7 is the one that's useful, and is applicable to JWT, VCs, ..., any other JSON.

Questions are:
- should the structure presented in section 7 be the default one - there's a claim disclosures. (this also solves the issue with JWS mentioned above)
- should the structure in sec. 7 adopt syntax from JSON serialised JWS - introducing the disclosures claim in the payload 
- render the current JWS compact serialisation as a way to do SD when disclosures are unsigned and when size is an issue

With this we cover all cases in an unambiguous way
- JSON serialised JWS works as described. If disclosures need to be signed over, they can also be moved to the protected header
- JWS libs as they are can be used to sign and verify signatures of SD
- issuer can sign the disclosures (if required)
- holder can sign the disclosures (if required)
- if size limit is a constraint, there's an optimisation as presented in the document. Limitation: disclosures are unsigned

**Comment by mtaimela** [comment] 2023-06-15 20:31
Hi all,

I'm happy to see such a vibrant community, with multiple angles, thank you all for contributing into brainstorming. The SD-JWT design is great, and would definitely work, but the issue is open because I do think that it could be even better.

The section 7 also introduces the original issue of double encoding, which is why the tilde exists in first place. Luckily the JWS Compacted serialization is not the only option so I crafted the small examples for the [JWS Unencoded Payload](https://www.rfc-editor.org/rfc/rfc7797) WITH JWS Flattened serialization.

The actual structure for the wrapper can be anything, it contains SD-JWT as is (no double encoding), the Disclosures are signed, and the thing do not need new a content-type.

It is also good to refresh the memory that URI/URL components do not use content-type at all in HTTP, the media-type is meant for the HTTP body only. The SD-JWT + Disclosures with tilde will break all existing JWT parsers when transported outside of HTTP body, or the processing must be forced into application side and the tilde pre-processing must be instructed.

The Issuance "wrapper": replacing tilde and preserving everything else.
```javascript
{
  signature: 'u0OKqXBRq_hXhcKkmnZ5XGi3Lm9t2-2RpcjdGkocwo2u7bpCE0nJZ92DsBmCay-ZZij5lO5e6Ebk9WoG1zJsPg',
  payload: '{"sd":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvdjIiXSwiaWQiOiI5YmNjOWFhYS0zYmRjLTQ0MTQtOTQ1MC03MzljMjk1Yzc1MmMiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiU3R1ZGVudElEIl0sImlzc3VlciI6ImRpZDplYnNpOnp2SFdYMzU5QTNDdmZKbkNZYUFpQWRlIiwidmFsaWRGcm9tIjoiMjAyMy0wMS0wMVQwMDowMDowMFoiLCJ2YWxpZFVudGlsIjoiMjAzMy0wMS0wMVQwMDowMDowMFoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDprZXk6Li4uIiwiX3NkIjpbInpTbUltV0hQSnpRN1J4OFpHMElZaFVGMU96ajhmMTd3REtKR2h4VWtyZFUiLCJUNFJuRG0xY2xWTENhdjJNcnNlbDZzTk16OHBxR0NlTXJycF9fWXJWXy13IiwiU0ZRVGpyOTFJa1BpNmJldFEwRVlzNXJkSjJUYk1lc0pHZnRGNmg3aGpUQSJdLCJzdHVkZW50Ijp0cnVlfX0.qbKCK100Pqg1fJPKS1QXmI4u1bwPQSMewMQxzD19sf4qgk_hIWQRBy4BTbADYrQa30ct8no0dhV--PZREkjf5A","disclosures":["WyIyR0xDNDJzS1F2ZUNmR2ZyeU5STjl3IiwgImZhbWlseU5hbWUiLCAiQ2Fycm9sbCJd","WyJlbHVWNU9nM2dTTklJOEVZbnN4QV9BIiwgImdpdmVuTmFtZSIsICJMZXdpcyJd","WyI2SWo3dE0tYTVpVlBHYm9TNXRtdlZBIiwgImJpcnRoRGF0ZSIsICIxODMyLTAxLTI3Il0"]}',
  protected: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19'
}
```

JWK keys for validation
```javascript
{
  kty: "EC",
  d: "z617Hhdusxqt3KN98NHvFtWTpSW_sq2cCZpNSzu8m88",
  crv: "P-256",
  x: "ZYE6uX3XvQ9rLc6s0eeo2YiOM2VfwrEZOZXzTOthcHE",
  y: "k-t1bfe-MmmXWQ0QaxK3uJMYlMNkJHYGUSLpxP9RQak"
}
```

**Comment by danielfett** [comment] 2023-06-19 16:57
@alenhorvat I'm not sure I fully understand your proposal. You say:

> JSON serialised JWS works as described. If disclosures need to be signed over, they can also be moved to the protected header

Then the signature would break once the Holder removes any Disclosures.

@mtaimela As I said above, we are not concerned about the transfer of SD-JWTs over actual URLs. We are concerned about places where the character set is limited to URL-safe characters like an OAuth bearer token. That would require another round of base64url-encoding the proposed format.

And while I do appreciate the input of both of you and your thoughts about these alternative formats, let me address two important points:

 - We're not breaking the JWS parser in any way. The current format is just not meant to be fed into an JWS parser directly, and that is perfectly fine. The JWS parser in the current format is meant to run after extracting the various parts.
 - SD-JWT has gained a lot of momentum in the past months and there is a lot of "running code" already. We are not willing to break existing implementations in a substantial way, and any breaking change must provide tangible advantages. In its current form, SD-JWT provides an extremely simple-to-understand, compact format that serves many use cases really well. Yes, the disclosures are not signed over, but I do not think that this is a good enough reason to completely change the format. I'm happy to discuss what is defined in Section 7 and 8 (as the less-used alternatives to the current default format), and I'm happy to discuss a hash over the disclosures (although I'm still not convinced), but I honestly do not see the default format changing substantially in the future unless there is a working group consensus to do so.

**Comment by alenhorvat** [comment] 2023-06-19 17:19
> @alenhorvat I'm not sure I fully understand your proposal. You say:
> 
> > JSON serialised JWS works as described. If disclosures need to be signed over, they can also be moved to the protected header
> 
> Then the signature would break once the Holder removes any Disclosures.
> 
> @mtaimela As I said above, we are not concerned about the transfer of SD-JWTs over actual URLs. We are concerned about places where the character set is limited to URL-safe characters like an OAuth bearer token. That would require another round of base64url-encoding the proposed format.
> 
> And while I do appreciate the input of both of you and your thoughts about these alternative formats, let me address two important points:
> 
> * We're not breaking the JWS parser in any way. The current format is just not meant to be fed into an JWS parser directly, and that is perfectly fine. The JWS parser in the current format is meant to run after extracting the various parts.
> * SD-JWT has gained a lot of momentum in the past months and there is a lot of "running code" already. We are not willing to break existing implementations in a substantial way, and any breaking change must provide tangible advantages. In its current form, SD-JWT provides an extremely simple-to-understand, compact format that serves many use cases really well. Yes, the disclosures are not signed over, but I do not think that this is a good enough reason to completely change the format. I'm happy to discuss what is defined in Section 7 and 8 (as the less-used alternatives to the current default format), and I'm happy to discuss a hash over the disclosures (although I'm still not convinced), but I honestly do not see the default format changing substantially in the future unless there is a working group consensus to do so.

Hi, @danielfett. Thank you for the swift reply. JSON serialisation supports multiple signatures. First protects the SD-JWT, as today, second one protects the whole payload.

> We are concerned about places where the character set is limited to URL-safe characters like an OAuth bearer token. That would require another round of base64url-encoding the proposed format.

This sounds like an interesting use case. Can you elaborate in which scenarios SD-JWTs would be transferred as bearer tokens?

> We're not breaking the JWS parser in any way. The current format is just not meant to be fed into an JWS parser directly, and that is perfectly fine. The JWS parser in the current format is meant to run after extracting the various parts.

My concern is that in the limit, where noting is hidden, extra 'tilde' is still required and with it another serialisation - even though that doesn't have to be the case. We can (at least in our use cases) always go with JSON serialisation and leave the compact for the cases where there's no other option.

**Comment by alenhorvat** [comment] 2023-06-23 15:39
Hi. Can we make a PR with the proposal mentioned in this issue?

**Comment by bc-pi** [comment] 2023-06-23 20:55
> Hi. Can we make a PR with the proposal mentioned in this issue?

There is not, as far as I can tell, a tangible cohesive proposal mentioned in this issue for which a PR could be made. And the various piecemeal suggestions have received polite but firm push-back from the draft editors (who are also representing the working group rough consensus on the draft). As such, I don't think a PR here is appropriate. If you really believe there is a coherent proposal that can be expressed more clearly in a PR, then you are free to create one (of course). But please set your expectations accordingly and realize that it likely will not be accepted.

**Closed by bc-pi** 2023-06-23 20:55 UTC
Labels: pending-close

**Comment by Sakurann** [comment] 2023-06-28 16:45
> Is there a reason why the Disclosures cannot be signed? If there is no reason to NOT sign the Disclosures, then I do propose an alternative design.
>
> There could be a Holder Disclosed VC or so to aggregate the Issuer-Issued Disclosure AND SD-JWT. This will fit into the normal way of treating VCs, stored as is and queried through VP exchange.

you can still do this. there is [an entire section on "Enveloping"](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#name-enveloping-sd-jwts) which allows you to do this
